# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

            - name: Install node.js v20
              uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
              with:
                  node-version: 20
                  cache: 'yarn'
                  cache-dependency-path: yarn.lock

            - name: Install dependencies
              run: yarn --immutable

            - name: Run linters
              uses: wearerequired/lint-action@548d8a7c4b04d3553d32ed5b6e91eb171e10e7bb # v2
              with:
                  eslint: true
                  eslint_extensions: js,ts
                  auto_fix: true
                  commit_message: 'chore(ci): ${linter} issues fix'
