name: Publish Package to npmjs

on:
    release:
        types:
            - published

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Install node.js v20
              uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
              with:
                  node-version: 20
                  cache: yarn
                  registry-url: https://registry.yarnpkg.com/

            - name: Install dependencies
              run: yarn --immutable

            - name: Publish to npm
              run: |
                  yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
                  yarn config set npmPublishRegistry "https://registry.yarnpkg.com"
                  yarn npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
